{
 "title": "rDNS Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "dsource",
    "label": "Data Source",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Queried domains",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT timestamp, groupArray((Question, count)) FROM (SELECT (intDiv(toUInt32(t), 1) * 1) * 1000  as timestamp, Question, sum(c) as count FROM DNS_DOMAIN_COUNT WHERE DnsDate >= toDate(1506625902) AND t >= toDateTime(1506625902) AND Server IN('default','valparaiso') group by t, Question ORDER BY count desc limit 5 by timestamp) GROUP BY timestamp\n ORDER BY timestamp",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "t",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkseagreen\">timestamp</font>, <font color=\"navajowhite\">groupArray</font>((Question, <font color=\"navajowhite\">count</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font>  <font color=\"darkorange\">as</font> <font color=\"darkseagreen\">timestamp</font>, Question, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>) <font color=\"darkorange\">group by</font> t, Question <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">desc</font> <font color=\"darkorange\">limit</font> <font color=\"cornflowerblue\">5</font> by <font color=\"darkseagreen\">timestamp</font>) <font color=\"darkorange\">group by</font> <font color=\"darkseagreen\">timestamp</font><br /> <font color=\"darkorange\">order by</font> <font color=\"darkseagreen\">timestamp</font>",
     "query": "SELECT timestamp, groupArray((Question, count)) FROM (SELECT $timeSeries  as timestamp, Question, sum(c) as count FROM DNS_DOMAIN_COUNT WHERE $timeFilter  group by t, Question ORDER BY count desc limit 5 by timestamp) GROUP BY timestamp\n ORDER BY timestamp",
     "rawQuery": "SELECT timestamp, groupArray((Question, count)) FROM (SELECT (intDiv(toUInt32(t), 1) * 1) * 1000  as timestamp, Question, sum(c) as count FROM default.DNS_DOMAIN_COUNT WHERE DnsDate >= toDate(1506436944) AND t >= toDateTime(1506436944) AND Server IN('valparaiso') group by t, Question ORDER BY count desc limit 5 by timestamp) group by timestamp  order by timestamp",
     "table": "DNS_DOMAIN_COUNT",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique Domains Queried Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, uniqMerge(UniqueDnsCount)/2 as Count  FROM DNS_DOMAIN_UNIQUE WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   GROUP BY t ORDER BY t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, uniqMerge(UniqueDnsCount)<font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font> <font color=\"darkorange\">as</font> Count  <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">GROUP BY</font> t <font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT $timeSeries as t, uniqMerge(UniqueDnsCount)/$interval as Count  FROM DNS_DOMAIN_UNIQUE WHERE $timeFilter    GROUP BY t ORDER BY t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, uniqMerge(UniqueDnsCount)/2 as Count  FROM default.DNS_DOMAIN_UNIQUE WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   GROUP BY t ORDER BY t",
     "table": "DNS_DOMAIN_UNIQUE",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Packet Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, avgMerge(AverageSize) AS Bytes FROM DNS_GENERAL_AGGREGATIONS WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   Group by t order by t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, avgMerge(AverageSize) <font color=\"darkorange\">AS</font> Bytes <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">Group by</font> t <font color=\"darkorange\">order by</font> t",
     "query": "SELECT $timeSeries as t, avgMerge(AverageSize) AS Bytes FROM DNS_GENERAL_AGGREGATIONS WHERE $timeFilter    Group by t order by t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, avgMerge(AverageSize) AS Bytes FROM default.DNS_GENERAL_AGGREGATIONS WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   Group by t order by t",
     "table": "DNS_GENERAL_AGGREGATIONS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Packet Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, sumMerge(TotalSize)*8/2 as \"Bytes/s\" FROM DNS_GENERAL_AGGREGATIONS WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   Group by t order by t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "SELECT $timeSeries as t, sumMerge(TotalSize)*8/$interval as \"Bytes/s\" FROM $table   WHERE $timeFilter    Group by t order by t",
     "query": "SELECT $timeSeries as t, sumMerge(TotalSize)*8/$interval as \"Bytes/s\" FROM DNS_GENERAL_AGGREGATIONS WHERE $timeFilter    Group by t order by t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, sumMerge(TotalSize)*8/2 as \"Bytes/s\" FROM default.DNS_GENERAL_AGGREGATIONS   WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   Group by t order by t",
     "table": "DNS_GENERAL_AGGREGATIONS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Count byIP Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT t, groupArray((IPVersion, count/2)) FROM (SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, IPVersion, sum(c) as count FROM DNS_IP_MASK WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   group by t, IPVersion ORDER BY t) group by t\n order by t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((IPVersion, <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, IPVersion, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, IPVersion <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((IPVersion, count/$interval)) FROM (SELECT $timeSeries as t, IPVersion, sum(c) as count FROM DNS_IP_MASK WHERE $timeFilter    group by t, IPVersion ORDER BY t) group by t\n order by t",
     "rawQuery": "SELECT t, groupArray((IPVersion, count/4)) FROM (SELECT (intDiv(toUInt32(timestamp), 4) * 4) * 1000 as t, IPVersion, sum(c) as count FROM default.DNS_IP_MASK WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   group by t, IPVersion ORDER BY t) group by t  order by t",
     "table": "DNS_IP_MASK",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Count by Transport Protocol",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT t, groupArray((Protocol, count/2)) FROM (SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, Protocol, sum(c) as count FROM DNS_PROTOCOL WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   group by t, Protocol ORDER BY t) group by t\n order by t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((Protocol, <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, Protocol, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, Protocol <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((Protocol, count/$interval)) FROM (SELECT $timeSeries as t, Protocol, sum(c) as count FROM DNS_PROTOCOL WHERE $timeFilter    group by t, Protocol ORDER BY t) group by t\n order by t",
     "rawQuery": "SELECT t, groupArray((Protocol, count/4)) FROM (SELECT (intDiv(toUInt32(timestamp), 4) * 4) * 1000 as t, Protocol, sum(c) as count FROM default.DNS_PROTOCOL WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   group by t, Protocol ORDER BY t) group by t  order by t",
     "table": "DNS_PROTOCOL",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IPv4 Packet Destination Prefix",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "compiledQuery": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv4NumToString(IPPrefix) AS IP,\nsum(c) as total FROM DNS_IP_MASK PREWHERE IPVersion=4 WHERE DnsDate >= toDate(1506625362) AND timestamp >= toDateTime(1506625362) AND Server IN('default','valparaiso')     GROUP BY IPPrefix order by IPPrefix)",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"cornflowerblue\">0</font>, <font color=\"navajowhite\">groupArray</font>((IP, total)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"navajowhite\">IPv4NumToString</font>(IPPrefix) <font color=\"darkorange\">AS</font> IP,<br /><font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> total <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">PREWHERE</font> IPVersion<font color=\"yellow\">=</font><font color=\"cornflowerblue\">4</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)     <font color=\"darkorange\">GROUP BY</font> IPPrefix <font color=\"darkorange\">order by</font> IPPrefix)",
     "query": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv4NumToString(IPPrefix) AS IP,\nsum(c) as total FROM DNS_IP_MASK PREWHERE IPVersion=4 WHERE $timeFilter      GROUP BY IPPrefix order by IPPrefix)",
     "rawQuery": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv4NumToString(IPPrefix) AS IP, sum(c) as total FROM default.DNS_IP_MASK PREWHERE IPVersion=4 WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')     GROUP BY IPPrefix order by IPPrefix)",
     "table": "DNS_IP_MASK",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IPv6 Packet Destination Top 20 Prefix",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "compiledQuery": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv6NumToString(toFixedString(unhex(hex(IPPrefix)), 16)) AS IP,\nsum(c) as total FROM DNS_IP_MASK PREWHERE IPVersion=6 WHERE DnsDate >= toDate(1506625362) AND timestamp >= toDateTime(1506625362) AND Server IN('default','valparaiso')    GROUP BY IPPrefix order by IPPrefix desc limit 20)",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"cornflowerblue\">0</font>, <font color=\"navajowhite\">groupArray</font>((IP, total)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"navajowhite\">IPv6NumToString</font>(<font color=\"navajowhite\">toFixedString</font>(<font color=\"navajowhite\">unhex</font>(<font color=\"navajowhite\">hex</font>(IPPrefix)), <font color=\"cornflowerblue\">16</font>)) <font color=\"darkorange\">AS</font> IP,<br /><font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> total <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">PREWHERE</font> IPVersion<font color=\"yellow\">=</font><font color=\"cornflowerblue\">6</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)    <font color=\"darkorange\">GROUP BY</font> IPPrefix <font color=\"darkorange\">order by</font> IPPrefix <font color=\"darkorange\">desc</font> <font color=\"darkorange\">limit</font> <font color=\"cornflowerblue\">20</font>)",
     "query": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv6NumToString(toFixedString(unhex(hex(IPPrefix)), 16)) AS IP,\nsum(c) as total FROM DNS_IP_MASK PREWHERE IPVersion=6 WHERE $timeFilter     GROUP BY IPPrefix order by IPPrefix desc limit 20)",
     "rawQuery": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv6NumToString(toFixedString(unhex(hex(IPPrefix)), 16)) AS IP, sum(c) as total FROM default.DNS_IP_MASK PREWHERE IPVersion=6 WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')    GROUP BY IPPrefix order by IPPrefix desc limit 20)",
     "table": "DNS_IP_MASK",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS Question Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT t, groupArray((dictGetString('dns_type', 'Name', toUInt64(Type)), count/2)) FROM (SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, Type, sum(c) as count FROM DNS_TYPE WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   group by t, Type ORDER BY t) group by t\n order by t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((<font color=\"navajowhite\">dictGetString</font>(<font color=\"lightgreen\">'dns_type'</font>, <font color=\"lightgreen\">'Name'</font>, <font color=\"navajowhite\">toUInt64</font>(<font color=\"darkorange\">Type</font>)), <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, <font color=\"darkorange\">Type</font>, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, <font color=\"darkorange\">Type</font> <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((dictGetString('dns_type', 'Name', toUInt64(Type)), count/$interval)) FROM (SELECT $timeSeries as t, Type, sum(c) as count FROM DNS_TYPE WHERE $timeFilter    group by t, Type ORDER BY t) group by t\n order by t",
     "rawQuery": "SELECT t, groupArray((dictGetString('dns_type', 'Name', toUInt64(Type)), count/2)) FROM (SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, Type, sum(c) as count FROM default.DNS_TYPE WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   group by t, Type ORDER BY t) group by t  order by t",
     "table": "DNS_TYPE",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Class",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT t, groupArray((dictGetString('dns_class', 'Name', toUInt64(Class)), count/2)) FROM (SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, Class, sum(c) as count FROM DNS_CLASS WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   group by t, Class ORDER BY t) group by t\n order by t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((<font color=\"navajowhite\">dictGetString</font>(<font color=\"lightgreen\">'dns_class'</font>, <font color=\"lightgreen\">'Name'</font>, <font color=\"navajowhite\">toUInt64</font>(Class)), <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, Class, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, Class <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((dictGetString('dns_class', 'Name', toUInt64(Class)), count/$interval)) FROM (SELECT $timeSeries as t, Class, sum(c) as count FROM DNS_CLASS WHERE $timeFilter    group by t, Class ORDER BY t) group by t\n order by t",
     "rawQuery": "SELECT t, groupArray((dictGetString('dns_class', 'Name', toUInt64(Class)), count/2)) FROM (SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, Class, sum(c) as count FROM default.DNS_CLASS WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   group by t, Class ORDER BY t) group by t  order by t",
     "table": "DNS_CLASS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT t, groupArray((dictGetString('dns_responce', 'Name', toUInt64(ResponceCode)), count/2)) FROM (SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, ResponceCode, sum(c) as count FROM DNS_RESPONCECODE WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   group by t, ResponceCode ORDER BY t) group by t\n order by t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((<font color=\"navajowhite\">dictGetString</font>(<font color=\"lightgreen\">'dns_responce'</font>, <font color=\"lightgreen\">'Name'</font>, <font color=\"navajowhite\">toUInt64</font>(ResponceCode)), <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, ResponceCode, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, ResponceCode <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((dictGetString('dns_responce', 'Name', toUInt64(ResponceCode)), count/$interval)) FROM (SELECT $timeSeries as t, ResponceCode, sum(c) as count FROM DNS_RESPONCECODE WHERE $timeFilter    group by t, ResponceCode ORDER BY t) group by t\n order by t",
     "rawQuery": "SELECT t, groupArray((dictGetString('dns_responce', 'Name', toUInt64(ResponceCode)), count/2)) FROM (SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, ResponceCode, sum(c) as count FROM default.DNS_RESPONCECODE WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   group by t, ResponceCode ORDER BY t) group by t  order by t",
     "table": "DNS_RESPONCECODE",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpCode Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT t, groupArray((dictGetString('dns_opcode', 'Name', toUInt64(OpCode)), count/2)) FROM (SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, OpCode, sum(c) as count FROM DNS_OPCODE WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   group by t, OpCode ORDER BY t) group by t\n order by t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((<font color=\"navajowhite\">dictGetString</font>(<font color=\"lightgreen\">'dns_opcode'</font>, <font color=\"lightgreen\">'Name'</font>, <font color=\"navajowhite\">toUInt64</font>(OpCode)), <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, OpCode, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, OpCode <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((dictGetString('dns_opcode', 'Name', toUInt64(OpCode)), count/$interval)) FROM (SELECT $timeSeries as t, OpCode, sum(c) as count FROM DNS_OPCODE WHERE $timeFilter    group by t, OpCode ORDER BY t) group by t\n order by t",
     "rawQuery": "SELECT t, groupArray((dictGetString('dns_opcode', 'Name', toUInt64(OpCode)), count/4)) FROM (SELECT (intDiv(toUInt32(timestamp), 4) * 4) * 1000 as t, OpCode, sum(c) as count FROM default.DNS_OPCODE WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   group by t, OpCode ORDER BY t) group by t  order by t",
     "table": "DNS_OPCODE",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Edns0 Present in Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, sumMerge(EdnsCount)/2 as Edns0Present FROM DNS_EDNS WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')   GROUP BY t ORDER BY t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, sumMerge(EdnsCount)<font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font> <font color=\"darkorange\">as</font> Edns0Present <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">GROUP BY</font> t <font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT $timeSeries as t, sumMerge(EdnsCount)/$interval as Edns0Present FROM DNS_EDNS WHERE $timeFilter    GROUP BY t ORDER BY t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, sumMerge(EdnsCount)/2 as Edns0Present FROM default.DNS_EDNS WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')   GROUP BY t ORDER BY t",
     "table": "DNS_EDNS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DoBit Present in Packet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "compiledQuery": "SELECT (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t, sumMerge(DoBitCount)/2 as DoBitSet FROM DNS_EDNS WHERE DnsDate >= toDate(1506625902) AND timestamp >= toDateTime(1506625902) AND Server IN('default','valparaiso')  GROUP BY t ORDER BY t",
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, sumMerge(DoBitCount)<font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font> <font color=\"darkorange\">as</font> DoBitSet <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)  <font color=\"darkorange\">GROUP BY</font> t <font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT $timeSeries as t, sumMerge(DoBitCount)/$interval as DoBitSet FROM DNS_EDNS WHERE $timeFilter   GROUP BY t ORDER BY t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 4) * 4) * 1000 as t, sumMerge(DoBitCount)/4 as DoBitSet FROM default.DNS_EDNS WHERE DnsDate >= toDate(1506436944) AND timestamp >= toDateTime(1506436944) AND Server IN('valparaiso')  GROUP BY t ORDER BY t",
     "table": "DNS_EDNS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}