// DNSEvent is the wire format for DNS events between dnsmonster components.
// It carries pre-extracted index fields for fast filtering plus the full
// DNS message in wire format for deep inspection when needed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/dnsevent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNSEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata
	TimestampNs  int64  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // Unix timestamp in nanoseconds
	SrcIp        []byte `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`                    // 4 bytes (IPv4) or 16 bytes (IPv6)
	DstIp        []byte `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort      uint32 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort      uint32 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	IpVersion    uint32 `protobuf:"varint,6,opt,name=ip_version,json=ipVersion,proto3" json:"ip_version,omitempty"` // 4 or 6
	Protocol     string `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`                     // "udp" or "tcp"
	PacketLength uint32 `protobuf:"varint,8,opt,name=packet_length,json=packetLength,proto3" json:"packet_length,omitempty"`
	Identity     string `protobuf:"bytes,9,opt,name=identity,proto3" json:"identity,omitempty"` // server identity from dnstap
	Version      string `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`  // server version from dnstap
	// Pre-extracted DNS fields for hot-path filtering.
	// Most detection rules only need these — no dns_wire unpacking required.
	Qname      string `protobuf:"bytes,11,opt,name=qname,proto3" json:"qname,omitempty"`                              // First question name (e.g. "example.com.")
	Qtype      uint32 `protobuf:"varint,12,opt,name=qtype,proto3" json:"qtype,omitempty"`                             // DNS query type (1=A, 28=AAAA, 16=TXT, etc.)
	Rcode      uint32 `protobuf:"varint,13,opt,name=rcode,proto3" json:"rcode,omitempty"`                             // Response code (0=NOERROR, 3=NXDOMAIN, etc.)
	IsResponse bool   `protobuf:"varint,14,opt,name=is_response,json=isResponse,proto3" json:"is_response,omitempty"` // true if QR=1 (response), false if query
	// Full DNS message in RFC 1035 wire format (dns.Msg.Pack() output).
	// Consumers needing answer records, authority section, EDNS options,
	// or any field not pre-extracted above unpack this on demand via
	// dns.Msg.Unpack(dns_wire). ~100-500 bytes per message.
	DnsWire       []byte `protobuf:"bytes,15,opt,name=dns_wire,json=dnsWire,proto3" json:"dns_wire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSEvent) Reset() {
	*x = DNSEvent{}
	mi := &file_proto_dnsevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSEvent) ProtoMessage() {}

func (x *DNSEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dnsevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSEvent.ProtoReflect.Descriptor instead.
func (*DNSEvent) Descriptor() ([]byte, []int) {
	return file_proto_dnsevent_proto_rawDescGZIP(), []int{0}
}

func (x *DNSEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *DNSEvent) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *DNSEvent) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *DNSEvent) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *DNSEvent) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *DNSEvent) GetIpVersion() uint32 {
	if x != nil {
		return x.IpVersion
	}
	return 0
}

func (x *DNSEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DNSEvent) GetPacketLength() uint32 {
	if x != nil {
		return x.PacketLength
	}
	return 0
}

func (x *DNSEvent) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *DNSEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DNSEvent) GetQname() string {
	if x != nil {
		return x.Qname
	}
	return ""
}

func (x *DNSEvent) GetQtype() uint32 {
	if x != nil {
		return x.Qtype
	}
	return 0
}

func (x *DNSEvent) GetRcode() uint32 {
	if x != nil {
		return x.Rcode
	}
	return 0
}

func (x *DNSEvent) GetIsResponse() bool {
	if x != nil {
		return x.IsResponse
	}
	return false
}

func (x *DNSEvent) GetDnsWire() []byte {
	if x != nil {
		return x.DnsWire
	}
	return nil
}

var File_proto_dnsevent_proto protoreflect.FileDescriptor

const file_proto_dnsevent_proto_rawDesc = "" +
	"\n" +
	"\x14proto/dnsevent.proto\x12\n" +
	"dnsmonster\"\xa5\x03\n" +
	"\bDNSEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\rR\adstPort\x12\x1d\n" +
	"\n" +
	"ip_version\x18\x06 \x01(\rR\tipVersion\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\x12#\n" +
	"\rpacket_length\x18\b \x01(\rR\fpacketLength\x12\x1a\n" +
	"\bidentity\x18\t \x01(\tR\bidentity\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion\x12\x14\n" +
	"\x05qname\x18\v \x01(\tR\x05qname\x12\x14\n" +
	"\x05qtype\x18\f \x01(\rR\x05qtype\x12\x14\n" +
	"\x05rcode\x18\r \x01(\rR\x05rcode\x12\x1f\n" +
	"\vis_response\x18\x0e \x01(\bR\n" +
	"isResponse\x12\x19\n" +
	"\bdns_wire\x18\x0f \x01(\fR\adnsWireB&Z$github.com/mosajjal/dnsmonster/protob\x06proto3"

var (
	file_proto_dnsevent_proto_rawDescOnce sync.Once
	file_proto_dnsevent_proto_rawDescData []byte
)

func file_proto_dnsevent_proto_rawDescGZIP() []byte {
	file_proto_dnsevent_proto_rawDescOnce.Do(func() {
		file_proto_dnsevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dnsevent_proto_rawDesc), len(file_proto_dnsevent_proto_rawDesc)))
	})
	return file_proto_dnsevent_proto_rawDescData
}

var file_proto_dnsevent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_dnsevent_proto_goTypes = []any{
	(*DNSEvent)(nil), // 0: dnsmonster.DNSEvent
}
var file_proto_dnsevent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dnsevent_proto_init() }
func file_proto_dnsevent_proto_init() {
	if File_proto_dnsevent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dnsevent_proto_rawDesc), len(file_proto_dnsevent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dnsevent_proto_goTypes,
		DependencyIndexes: file_proto_dnsevent_proto_depIdxs,
		MessageInfos:      file_proto_dnsevent_proto_msgTypes,
	}.Build()
	File_proto_dnsevent_proto = out.File
	file_proto_dnsevent_proto_goTypes = nil
	file_proto_dnsevent_proto_depIdxs = nil
}
